version: "3.3"

services:
  personal-discord-bot-yuri:
    container_name: personal-discord-bot-yuri
    build: .
    image: piket95/personal-discord-bot-yuri
    volumes:
      - ./volumes/assets:/app/assets
      - ./volumes/config:/app/config
      - ./volumes/data:/app/data
      - ./volumes/.env:/app/.env

# TODO: Volume Pfade fertig ausfüllen, sobald bekannt